services:
  - type: web
    name: kidney-classifier
    runtime: python
    env: python
    buildCommand: |
      pip install -r requirements.txt
      ./setup.sh
    startCommand: python app.py
    environment:
      pythonVersion: 3.9
